default:
  image: registry.gitlab.com/islandoftex/images/texlive:latest
  before_script:
    # install additional requirements for the validation procedure
    - apt-get update && apt-get install -y zip unzip default-jre wget && rm -rf /var/lib/apt/lists/*
    # download validate_zugferd.sh to support/ so it's not done multiple times later
    - cd support && bash validate_zugferd.sh && cd -
  after_script:
    # testfiles have already been validated, but DEMO did not
    - bash support/validate_zugferd.sh build/doc/DEMO*.pdf

.checktemplate:
  script:
    - l3build check
    - bash support/validate_zugferd.sh build/doc/DEMO*.pdf

check:
  extends: .checktemplate
  stage: test

check-pretest:
  extends: .checktemplate
  stage: test
  image: registry.gitlab.com/islandoftex/images/texlive:pretest

build_ctan:
  stage: deploy
  script:
    - l3build ctan
  artifacts:
    paths:
      - ./*.pdf
      - ./*.zip
