image: registry.gitlab.com/islandoftex/images/texlive:latest

check:
  stage: test
  before_script:
    - apt-get update && apt-get install -y zip unzip default-jre wget && rm -rf /var/lib/apt/lists/*
  script:
    - l3build doc
    - bash validate_zugferd.sh build/doc/DEMO*.pdf

build_ctan:
  stage: deploy
  before_script:
    - apt-get update && apt-get install -y zip unzip && rm -rf /var/lib/apt/lists/*
  script:
    - l3build ctan
  artifacts:
    paths:
      - ./*.pdf
      - ./*.zip

