name: Test and build CTAN

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install TeX Live
        uses: ${{ GITHUB_SERVER_URL == 'https://github.com' && 'actions' || 'https://github.com' }}/zauguin/install-texlive@v4
        with:
           package_file: .tl_packages
      # download validate_zugferd.sh to support/ so it's not done multiple times later
      - run: cd support && bash validate_zugferd.sh && cd -
      - run: l3build check
  doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install TeX Live
        uses: ${{ GITHUB_SERVER_URL == 'https://github.com' && 'actions' || 'https://github.com' }}/zauguin/install-texlive@v4
        with:
           package_file: .tl_packages
      # download validate_zugferd.sh to support/ so it's not done multiple times later
      - run: cd support && bash validate_zugferd.sh && cd -
      - run: l3build doc
      - run: bash support/validate_zugferd.sh build/doc/DEMO*.pdf
      - name: move pdf
        run: mkdir -p pdf-output && mv *.pdf pdf-output/.
      - uses: ${{ GITHUB_SERVER_URL == 'https://github.com' && 'actions' || 'https://github.com' }}/crazy-max/ghaction-github-pages@v4
        # only publish pdf from main branch
        if: github.ref == 'refs/heads/main'
        with:
          target_branch: pdf-output
          build_dir: pdf-output
          domain: ${{ github.server_url }}
          commit_message: Publish PDF Output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ctan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install TeX Live
        uses: ${{ GITHUB_SERVER_URL == 'https://github.com' && 'actions' || 'https://github.com' }}/zauguin/install-texlive@v4
        with:
           package_file: .tl_packages
      # download validate_zugferd.sh to support/ so it's not done multiple times later
      - run: cd support && bash validate_zugferd.sh && cd -
      - run: l3build ctan
      - name: Upload build artifats
        # temporary workaround for forgejo ci
        uses: ${{ GITHUB_SERVER_URL == 'https://github.com' && 'actions' || 'https://code.forgejo.org/forgejo' }}/upload-artifact@v4
        with:
          name: zugferd-ctan.zip
          path: "build/distrib/ctan/zugferd/"
