name: Build CTAN

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: check
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
           package_file: .tl_packages
      # download validate_zugferd.sh to support/ so it's not done multiple times later
      - run: cd support && bash validate_zugferd.sh && cd -
      - run: l3build check
      - run: bash support/validate_zugferd.sh build/doc/DEMO*.pdf
      - name: Upload build artifats
        uses: actions/upload-artifact@v4
        with:
          name: zugferd-ctan
          path: "build/distrib/ctan/zugferd/"
